
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("a5ac8b7d-03db-417f-8a1c-629fe0cd3698")>
Namespace VB

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class DZUsersEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new DZUsersEntities object using the connection string found in the 'DZUsersEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=DZUsersEntities", "DZUsersEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new DZUsersEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "DZUsersEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new DZUsersEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "DZUsersEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property BranchUsers() As ObjectSet(Of BranchUser)
            Get
                If (_BranchUsers Is Nothing) Then
                    _BranchUsers = MyBase.CreateObjectSet(Of BranchUser)("BranchUsers")
                End If
                Return _BranchUsers
            End Get
        End Property
    
        Private _BranchUsers As ObjectSet(Of BranchUser)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Depts() As ObjectSet(Of Dept)
            Get
                If (_Depts Is Nothing) Then
                    _Depts = MyBase.CreateObjectSet(Of Dept)("Depts")
                End If
                Return _Depts
            End Get
        End Property
    
        Private _Depts As ObjectSet(Of Dept)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the BranchUsers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToBranchUsers(ByVal branchUser As BranchUser)
            MyBase.AddObject("BranchUsers", branchUser)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Depts EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToDepts(ByVal dept As Dept)
            MyBase.AddObject("Depts", dept)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DZUsersModel", Name:="BranchUser")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class BranchUser
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new BranchUser object.
        ''' </summary>
        ''' <param name="lastName">Initial value of the LastName property.</param>
        ''' <param name="firstName">Initial value of the FirstName property.</param>
        ''' <param name="dept">Initial value of the Dept property.</param>
        ''' <param name="xN">Initial value of the XN property.</param>
        ''' <param name="status">Initial value of the Status property.</param>
        ''' <param name="userName">Initial value of the UserName property.</param>
        Public Shared Function CreateBranchUser(lastName As Global.System.String, firstName As Global.System.String, dept As Global.System.String, xN As Global.System.String, status As Global.System.String, userName As Global.System.String) As BranchUser
            Dim branchUser as BranchUser = New BranchUser
            branchUser.LastName = lastName
            branchUser.FirstName = firstName
            branchUser.Dept = dept
            branchUser.XN = xN
            branchUser.Status = status
            branchUser.UserName = userName
            Return branchUser
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property LastName() As Global.System.String
            Get
                Return _LastName
            End Get
            Set
                OnLastNameChanging(value)
                ReportPropertyChanging("LastName")
                _LastName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("LastName")
                OnLastNameChanged()
            End Set
        End Property
    
        Private _LastName As Global.System.String
        Private Partial Sub OnLastNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLastNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FirstName() As Global.System.String
            Get
                Return _FirstName
            End Get
            Set
                OnFirstNameChanging(value)
                ReportPropertyChanging("FirstName")
                _FirstName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("FirstName")
                OnFirstNameChanged()
            End Set
        End Property
    
        Private _FirstName As Global.System.String
        Private Partial Sub OnFirstNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFirstNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Dept() As Global.System.String
            Get
                Return _Dept
            End Get
            Set
                OnDeptChanging(value)
                ReportPropertyChanging("Dept")
                _Dept = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Dept")
                OnDeptChanged()
            End Set
        End Property
    
        Private _Dept As Global.System.String
        Private Partial Sub OnDeptChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDeptChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property XN() As Global.System.String
            Get
                Return _XN
            End Get
            Set
                OnXNChanging(value)
                ReportPropertyChanging("XN")
                _XN = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("XN")
                OnXNChanged()
            End Set
        End Property
    
        Private _XN As Global.System.String
        Private Partial Sub OnXNChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnXNChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Phone() As Global.System.String
            Get
                Return _Phone
            End Get
            Set
                OnPhoneChanging(value)
                ReportPropertyChanging("Phone")
                _Phone = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Phone")
                OnPhoneChanged()
            End Set
        End Property
    
        Private _Phone As Global.System.String
        Private Partial Sub OnPhoneChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPhoneChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property DZCellPhone() As Global.System.String
            Get
                Return _DZCellPhone
            End Get
            Set
                OnDZCellPhoneChanging(value)
                ReportPropertyChanging("DZCellPhone")
                _DZCellPhone = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("DZCellPhone")
                OnDZCellPhoneChanged()
            End Set
        End Property
    
        Private _DZCellPhone As Global.System.String
        Private Partial Sub OnDZCellPhoneChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDZCellPhoneChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Email() As Global.System.String
            Get
                Return _Email
            End Get
            Set
                OnEmailChanging(value)
                ReportPropertyChanging("Email")
                _Email = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Email")
                OnEmailChanged()
            End Set
        End Property
    
        Private _Email As Global.System.String
        Private Partial Sub OnEmailChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnEmailChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Status() As Global.System.String
            Get
                Return _Status
            End Get
            Set
                OnStatusChanging(value)
                ReportPropertyChanging("Status")
                _Status = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Status")
                OnStatusChanged()
            End Set
        End Property
    
        Private _Status As Global.System.String
        Private Partial Sub OnStatusChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnStatusChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property EmpType() As Global.System.String
            Get
                Return _EmpType
            End Get
            Set
                OnEmpTypeChanging(value)
                ReportPropertyChanging("EmpType")
                _EmpType = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("EmpType")
                OnEmpTypeChanged()
            End Set
        End Property
    
        Private _EmpType As Global.System.String
        Private Partial Sub OnEmpTypeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnEmpTypeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property MgrID() As Global.System.String
            Get
                Return _MgrID
            End Get
            Set
                OnMgrIDChanging(value)
                ReportPropertyChanging("MgrID")
                _MgrID = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("MgrID")
                OnMgrIDChanged()
            End Set
        End Property
    
        Private _MgrID As Global.System.String
        Private Partial Sub OnMgrIDChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnMgrIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property UserName() As Global.System.String
            Get
                Return _UserName
            End Get
            Set
                If (_UserName <> Value) Then
                    OnUserNameChanging(value)
                    ReportPropertyChanging("UserName")
                    _UserName = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("UserName")
                    OnUserNameChanged()
                End If
            End Set
        End Property
    
        Private _UserName As Global.System.String
        Private Partial Sub OnUserNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnUserNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property SAPID() As Global.System.String
            Get
                Return _SAPID
            End Get
            Set
                OnSAPIDChanging(value)
                ReportPropertyChanging("SAPID")
                _SAPID = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("SAPID")
                OnSAPIDChanged()
            End Set
        End Property
    
        Private _SAPID As Global.System.String
        Private Partial Sub OnSAPIDChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnSAPIDChanged()
        End Sub

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DZUsersModel", Name:="Dept")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Dept
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Dept object.
        ''' </summary>
        ''' <param name="dept1">Initial value of the Dept1 property.</param>
        Public Shared Function CreateDept(dept1 As Global.System.String) As Dept
            Dim dept as Dept = New Dept
            dept.Dept1 = dept1
            Return dept
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Dept1() As Global.System.String
            Get
                Return _Dept1
            End Get
            Set
                If (_Dept1 <> Value) Then
                    OnDept1Changing(value)
                    ReportPropertyChanging("Dept1")
                    _Dept1 = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("Dept1")
                    OnDept1Changed()
                End If
            End Set
        End Property
    
        Private _Dept1 As Global.System.String
        Private Partial Sub OnDept1Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDept1Changed()
        End Sub

        #End Region

    End Class

    #End Region

    
End Namespace
